---
include:
  - board: s40nc
  - board: le_jlwffre
  - board: pillbug
    shield: waka60
  - board: uwu30
  - board: qaz_rp2040
  - board: pillbug
    shield: bb40
  - board: pillbug
    shield: bb40
    cmake-args: "'-DCONFIG_ZMK_KEYBOARD_NAME=\"BB40 (Alien)\"'"
    artifact-name: bb40-alien
  - board: pillbug
    shield: bb40
    cmake-args: "'-DCONFIG_ZMK_KEYBOARD_NAME=\"BB40 (Pink)\"'"
    artifact-name: bb40-pink
  - board: pillbug
    shield: bb40
    cmake-args: "'-DCONFIG_ZMK_KEYBOARD_NAME=\"BB40 (Serika)\"'"
    artifact-name: bb40-serika
