# MechWild shields set up the global thread by default, but maybe other shields don't.
#CONFIG_EC11=y
#CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

### QOL SETTINGS ###

# Uncomment to avoid expanding macro expansion error messages. This can make build logs much, much more digestible for troubleshooting.
CONFIG_COMPILER_TRACK_MACRO_EXPANSION=n

# Uncomment to increase the transmit power of the keyboard's BLE radio.
# This will help if the connection to the host is poor/inconsistent.
#CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Uncomment and modify the number to change the number of BLE profiles/pairings.
# You probably don't want to set this at all if you ever build a split.
CONFIG_BT_MAX_CONN=8
CONFIG_BT_MAX_PAIRED=8

# Uncomment to enable passkey entry and unauth overwrite for improved security.
# MAKE SURE YOUR KEYMAP HAS ALL THE NUMBERS AVAILABLE. You will need to re-pair your keyboard with all hosts after enabling this.
CONFIG_ZMK_BLE_EXPERIMENTAL_SEC=y

# Uncomment to enable experimental BLE settings.
# What exactly these settings are will vary as ZMK development progresses, so CHECK BEFORE ENABLING. https://zmk.dev/docs/config/bluetooth#kconfig
#CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# Uncomment to enable soft-off.
CONFIG_ZMK_PM_SOFT_OFF=y

### POWER-SAVING SETTINGS ###

# How long before the board goes idle, which turns off LEDs and displays (ms). 300000 ms = 5 min.
#CONFIG_ZMK_IDLE_TIMEOUT=300000

# TODO: Straighten this out. Consider submitting a Kconfig change to turn sleep on by default on uwu30?
# In deep sleep the board will also disconnect from Bluetooth and cut external power.
# It may take several seconds for a board to wake from deep sleep after a key is pressed.
# Note: Deep sleep is currently PillBug/nice!nano-exclusive.
#CONFIG_ZMK_SLEEP=n

# How long the board will stay in idle mode before going to deep sleep (ms). 900000 ms = 15 min.
#CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

### RGB SETTINGS ###

# Uncomment to enable RGB.
# Note: RGB is PillBug/nice!nano-exclusive until a GPIO or PWM binding is created for the BlackPill boards.
#CONFIG_ZMK_RGB_UNDERGLOW=y
#CONFIG_WS2812_STRIP=y

# Uncommenting will allow you to turn RGB off without cutting power to the external power pin. This is useful when the display uses the same power source as the RGB LEDs.
# Unfortunately, it has a huge impact on battery life since the RGB LEDs draw significant power even when "turned off". Cutting power to the LEDs is the only way to prevent this.
# Not recommended for batteries under 500 mAh.
#CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# Uncomment to turn off RGB when the keyboard goes idle.
#CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# Uncomment to turn off RGB when the keyboard is disconnected from USB.
#CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y

### LOGGING SETTINGS ###

# Uncomment to increase the log buffer size. This may help if the log messages you're looking for seem to be getting dropped.
#CONFIG_LOG_BUFFER_SIZE=8192

# Uncomment to delay the log output. This may help catch issues close to startup.
#CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=3000

# TODO: Investigate dropping ZMK's default logging level....
#CONFIG_USB_CDC_ACM_LOG_LEVEL_WRN=y
