manifest:
  remotes:
    - name: lesshonor
      url-base: https://github.com/lesshonor
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: mechwild-zmk-keyboards
      remote: lesshonor
      revision: main
      clone-depth: 1
    - name: zmk
      remote: zmkfirmware
      revision: main
      clone-depth: 1
      import: app/west.yml
  self:
    path: config
