manifest:
  remotes:
    - name: lesshonor
      url-base: https://github.com/lesshonor
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: uwu30-zmk-config
      remote: lesshonor
      revision: cleanups
      clone-depth: 1
    - name: mechwild-zmk-keyboards
      remote: lesshonor
      revision: zephyr-3.5
      clone-depth: 1

    - name: vik-core-module
      remote: petejohanson
      revision: main
      clone-depth: 1

    - name: vik-controller-module
      remote: petejohanson
      revision: main
      clone-depth: 1

    - name: sadekbaroudi-keyboard-module
      remote: petejohanson
      revision: main
      clone-depth: 1

    - name: le-capybara-zmk-module
      remote: petejohanson
      revision: main
      clone-depth: 1

    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
      clone-depth: 1

    - name: zmk
      remote: zmkfirmware
      revision: pull/1995/merge
      clone-depth: 1
      import: app/west.yml
  self:
    path: config
